local_backend:
  url: http://localhost:8081/api/v1

backend:
  name: git-gateway
  branch: main
  quash_merges: true

media_folder: static/images
public_folder: /images

logo_url: https://avatars.githubusercontent.com/u/173496896

collections:
  - name: "admin"
    label: "Admin"
    files:
      - file: "src/data/info/site.json"
        label: "Site"
        name: "site"
        fields: 
          - {label: "Favicon", name: "favicon", widget: "image", required: false}
          - {label: "Goat Counter ID", name: "goatCounterId", widget: "string", required: false}
      - file: "src/data/info/artist.json"
        label: "Artist"
        name: "artist"
        fields: 
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Website URL", name: "websiteUrl", widget: "string"}
          - {label: "Store URL", name: "storeUrl", widget: "string", required: false}
          - {label: "Social Links", name: "socialLinks", widget: "list", field: {label: "Social Link", name: "socialLink", widget: "string"}}
          - {label: "Listening Links", name: "listeningLinks", widget: "list", field: {label: "Listening Link", name: "listeningLink", widget: "string"}}
  - name: "songs"
    label: "Songs"
    folder: "src/data/music/songs"
    create: true
    slug: "{{fields.slug}}"
    identifier_field: "name"
    format: "json"
    fields:
      - {label: "Slug", name: "slug", widget: "string", hint: "This will be used in the URL of the song page. E.g. 'yoursite.com/music/release-slug/**song-slug**'"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Duration (in seconds)", name: "durationInSeconds", widget: "number"}
      - {label: "Single Details", name: "singleDetails", widget: "object", fields: [
          {label: "Release Date", name: "releaseDate", widget: "datetime", format: "L", required: false},
          {label: "Cover Image", name: "coverImage", widget: "image", required: false}
        ], required: false}
      - {label: "Songwriting Credits", name: "songwritingCredits", widget: "list", field: {label: "Person", name: "person", widget: "relation", collection: "people", value_field: "name", display_fields: ["name"], search_fields: ["name"]}, required: false}
      - {label: "Personnel", name: "personnel", widget: "list", field: {label: "Person", name: "person", widget: "string"}, required: false}
      - {label: "YouTube Video ID", name: "youTubeVidId", widget: "string", required: false}
      - {label: "Lyrics", name: "lyrics", widget: "markdown", required: false}      
  - name: "releases"
    label: "Releases"
    folder: "src/data/music/releases"
    create: true
    slug: "{{fields.slug}}"
    identifier_field: "name"
    format: "json"
    fields:
      - {label: "Hide on site", name: "isHiddenOnSite", widget: "boolean", default: false, hint: "Check this box to prevent this release from being shown on the site."}
      - {label: "Slug", name: "slug", widget: "string", hint: "This will be used in the URL of the release page. E.g. 'yoursite.com/music/**release-slug**'"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Type", name: "type", widget: "select", options: ["LP", "EP"]}
      - {label: "Release Date", name: "releaseDate", widget: "datetime"}
      - {label: "Artwork", name: "artwork", widget: "object", fields: [
          {label: "Front", name: "front", widget: "image"},
          {label: "Back", name: "back", widget: "image", required: false},
          {label: "Artwork credit(s)", name: "credits", widget: "list", fields: [
          {label: "Person", name: "name", widget: "relation", collection: "people", value_field: "name", display_fields: ["name"], search_fields: ["name"]},
          {label: "Credit", name: "credit", widget: "string"}
      ], required: false}
        ]}
      - {label: "Recorded At", name: "recordedAt", widget: "list", fields: [
          {label: "Name", name: "name", widget: "string"},
          {label: "Link", name: "link", widget: "string", required: false}
        ], required: false}
      - {label: "Personnel", name: "personnel", widget: "list", fields: [
          {label: "Person", name: "name", widget: "relation", collection: "people", value_field: "name", display_fields: ["name"], search_fields: ["name"]},
          {label: "Credit", name: "credit", widget: "string"}
        ], required: false}
      - {label: "Purchase Link", name: "purchaseLink", widget: "string", required: false}
      - {label: "Listening Links", name: "listeningLinks", widget: "list", field: {label: "Listening Link", name: "listeningLink", widget: "string"}, required: false}
      - {label: "Songs", name: "songs", widget: "list", fields: [
          {label: "Song", name: "slug", widget: "relation", collection: "songs", value_field: "slug", display_fields: ["name"], search_fields: ["name"]}
        ], hint: "Add songs to this release by selecting them from the list above. Songs have to be created before they can be added to a release."}
      - {label: "Other Images", name: "otherImages", widget: "list", field: {label: "Image", name: "image", widget: "image"}, required: false}
  - name: "gigs"
    label: "Gigs"
    folder: "src/data/gigs"
    create: true
    slug: "{{fields.dateTime}}-{{fields.venue}}"
    identifier_field: "dateTime"
    format: "json"
    fields:
      - {label: "DateTime", name: "dateTime", widget: "datetime"}
      - {label: "Venue", name: "venue", widget: "string"}
      - {label: "Venue Address", name: "venueAddress", widget: "string"}
      - {label: "Ticket Link", name: "ticketLink", widget: "string", required: false}
  - name: "people"
    label: "People"
    folder: "src/data/people"
    create: true
    slug: "{{fields.name}}"
    identifier_field: "name"
    format: "json"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Link", name: "link", widget: "string", required: false}